---

name: Upload files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    continue-on-error: true
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies on Python ${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade pip
          pip install flake8-html

      - name: Run Flake8
        id: run_linters
        run: flake8
            --config=setup.cfg
            --exclude=app/books_management/migrations
            --format=html
            --htmldir=flake8-report .
        continue-on-error: true

      - name: Save flake8 HTML report
        uses: actions/upload-artifact@v3
        continue-on-error: true
        if: ${{ steps.run_linters.outcome == 'failure' }}
        with:
          name: flake-report_${{ matrix.python-version }}
          path: flake8-report/
